import SideBar from "@/components/common/side-bar";
import "./globals.css";
import { Inter } from "next/font/google";
import ReactQueryProvider from "@/contexts/react-query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen grid grid-cols-5">
          <SideBar />
          <main className="col-span-4 h-full py-4 px-3">
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
